version: '3'

services:
  # Eureka Service
  eureka-server:
    build:
      context: ./BACKEND-BLOG/Eureka-Server
    ports:
      - "8761:8761"
    networks:
      - n3

  # Gateway Service
  gateway-service:
    build:
      context: ./BACKEND-BLOG/Gateway
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    networks:
      - n3

  # MySQL Utilisateur
  mysql-utilisateur:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service-utilisateur
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - n3

  # MySQL Post
  mysql-post:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: service-post
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    networks:
      - n3

  # Utilisateur Service
  utilisateur-service:
    build:
      context: ./BACKEND-BLOG/Utilisateur
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server
      - mysql-utilisateur
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-utilisateur:3306/service-utilisateur
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 100
    networks:
      - n3

  # Post Service
  post-service:
    build:
      context: ./BACKEND-BLOG/POst
    ports:
      - "8089:8089"
    depends_on:
      - eureka-server
      - mysql-post
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-post:3306/service-post
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      eureka.client.serviceUrl.defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 100
    networks:
      - n3

  frontend:
    build:
      context: ./FRONT-END-BLOG
    ports:
      - "3000:80"
    depends_on:
      - post-service
      - utilisateur-service

  phpmyadmin-utilisateur:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql-utilisateur
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8082:80"
    networks:
      - n3

  phpmyadmin-post:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql-post
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8083:80"
    networks:
      - n3

networks:
  n3:
    external: true